### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by StephaneMangin**
A simple addition to this wonderful and simple tool now in french ^^

### CODE REVIEW

**Comment by jeblad** [comment]
Nice! :+1:

**Comment by mgedmin** [comment]
(Sorry for a long delay, I was on vacation and ignoring computers.)

This is :sparkles:amazing:sparkles:, thank you very much!

**Comment by mgedmin** [comment]
Would you like to create a PR adding yourself to https://github.com/gtimelog/gtimelog/blob/master/src/gtimelog/CONTRIBUTORS.rst?  (If not, that's fine, I'll do it myself.)

**Comment by StephaneMangin** [comment]
Done ^^

**Pull request merged**
