### PR TITLE
[FIX] Attribute error if `timelog` or `tasks` member have not yet bee…

### PR DESCRIPTION
**Pull request by codingforfun**
[FIX]

AttributeError: 'NoneType' object has no attribute 'check_reload'

### CODE REVIEW

**Comment by mgedmin** [comment]
Oh wow!  How come this problem never got triggered on my machine?

**Comment by codingforfun** [comment]
> Oh wow! How come this problem never got triggered on my machine?

It didn’t always happen on my machine either. 
Maybe it’s a timing issue. I don’t know. To be honest I didn’t really researched further. I just examined the place the error message occurred at. I think I won’t harm as is formally correct, therefore I didn’t investigate further.

**Comment by codingforfun** [comment]
Rebased onto master

**Comment by mgedmin** [comment]
Whoops, I thought I'd merged this already!

(I think what happened was the Merge button was disabled because the branch wasn't up-to-date wrt master, and I went into settings to turn off that useless merge requirement, and then forgot to go back and hit Merge.)

**Pull request merged**
