### PR TITLE
Add AppData file

### PR DESCRIPTION
**Pull request by amigadave**
AppData files are suggested when packaging desktop applications for Fedora, so here is a (very basic) one. It would be great to have translations and an extended description, but at least it's a start.

### CODE REVIEW

**Comment by mgedmin** [comment]
Thank you!

**Comment by mgedmin** [comment]
Small typo: It's -> Its.

I'm on a smartphone right now, can't fix it easily.

**Comment by amigadave** [comment]
Thanks for catching the typo. I copied it from http://mg.pov.lt/gtimelog/ (which is not an excuse, but it can be fixed there too).

**Comment by mgedmin** [comment]
Haha I thought it might've been something like it!  I was going to grep the source repo for the typo, but I completely forgot about the website.  Thanks for pointing it out!

**Pull request merged**
